// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbMN0bR2D76nQsKZmWC4zLewzRPoGYtz4',
    appId: '1:211143336428:web:7fd2771b27795eec6a60c9',
    messagingSenderId: '211143336428',
    projectId: 'final-exam-88aa7',
    authDomain: 'final-exam-88aa7.firebaseapp.com',
    storageBucket: 'final-exam-88aa7.appspot.com',
    measurementId: 'G-HXH0W4PVE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHFxCCmMwT0jNYeH2gw2IkkcqAAvGDPz4',
    appId: '1:211143336428:android:726ace9078018fb96a60c9',
    messagingSenderId: '211143336428',
    projectId: 'final-exam-88aa7',
    storageBucket: 'final-exam-88aa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEJNAhlN_rlzkz-1DTjMYoay6VcRvMPFE',
    appId: '1:211143336428:ios:cfca0999eb29fa2a6a60c9',
    messagingSenderId: '211143336428',
    projectId: 'final-exam-88aa7',
    storageBucket: 'final-exam-88aa7.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEJNAhlN_rlzkz-1DTjMYoay6VcRvMPFE',
    appId: '1:211143336428:ios:b155f45b6e4485d96a60c9',
    messagingSenderId: '211143336428',
    projectId: 'final-exam-88aa7',
    storageBucket: 'final-exam-88aa7.appspot.com',
    iosBundleId: 'com.example.finalExam.RunnerTests',
  );
}
